// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


// Mod
archives_base_name=JustEnoughMekanismMultiblocks
maven_group=gisellevonbingen.jei_mekanism_multiblocks
mod_id=jei_mekanism_multiblocks
mod_version=7.11
mod_name=Just Enough Mekanism Multiblocks
mod_description=Add JEI page for calculate mekanism multiblock cost
mod_license=MIT
mod_homepage=https://curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks
mod_source=https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks
mod_issues=https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues

// Minecraft, Mod Loader
mc_version=1.21.1
neoforge_loader_version=4
neoforge_api_version=21.1.200
neoforge_api_version_range=[21.1.194,)
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.sourcesets.enabled=false

// Implementation
mekanism_version=10.7.17.83
mekanism_version_range=[10.7.17,)
jei_version=19.21.0.247
better_fusion_file=6953128
mekanism_extra_file=7404505

// Runtime Only
refined_storage_file=5112710
jade_file=5639932
emi_version=1.1.19
